### ISSUE TITLE
安装后造成vsc无法使用。

### ISSUE THREAD

**Issue by SevenOfPaul** [CharlesZhang6/vscode-live2d#35]
![9834afb72750c1f36079aecc16995fe](https://user-images.githubusercontent.com/83870824/194998211-e1404362-97e3-4ec2-8759-55953994dcc2.png)

**Comment by SevenOfPaul** [comment]
Version: 1.72.0 (system setup)
Commit: 64bbfbf67ada9953918d72e1df2f4d8e537d340e
Date: 2022-10-04T23:20:39.912Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

**Comment by M1saka10010** [comment]
同样的情况，到1.72.2也没解决

**Comment by langyo** [comment]
same issue

**Comment by ghost** [comment]
![temporaryfix](https://user-images.githubusercontent.com/111584129/198569032-2ed3b4de-d704-4c39-95f8-397c8f9c0baa.png)

Hey guys, here's a fix, credit goes to **Fubuchi:**  **/** 你好说明，由DeepL 翻译。归功于Fubuchi，并感谢他。

**1.** - Go to 
`%localappdata%\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-sandbox\workbench\ `

**2.** - Edit "workbench.html", comment out  `<script src="../../../../vs/loader.js"></script>` **->**  `<!-- <script src="../../../../vs/loader.js"></script> -->`

**3.** - Save, the extension should now work.


**一** 进入 `%localappdata%\Programs\Microsoft VS Code\resources\appout\vs\code\electron-sandbox\workbench\`

**二** 编辑 "workbench.html"，注释掉 `<script src=".../.../.../vs/loader.js">  </script>` **->** `<!-- <script src="../../../../vs/loader.js"></script> -->`

**三** 保存，该扩展现在应该可以工作了。

### Important Note / 重要的是 ### 
If you make any changes, for example, the model height, model character, etc. the workbench.html will reset, so you'll need to add the comments again `<!-- -->` and save (otherwise VSCode won't run).

如果你做了任何改变，比如说。看板娘高度 , 自定义导入喜欢的模型url 等等。

workbench.html将被重置，所以你需要再次添加注释 `<!-- -->`并保存（否则VSCode将无法运行）。

**Comment by SevenOfPaul** [comment]
copy that。 thankyou
